services:
  redis:
    image: redis:alpine
    container_name: local-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: affiliate-proxy-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app # live-reload if you add nodemon
    command: npx nodemon --legacy-watch server.js
    environment:
      REDIS_URL: "redis://redis:6379"
      AFFILIATE_BASE_URL: "https://affiliate-network.com"
    depends_on:
      redis:
        condition: service_healthy
# Note:
# - Docker Compose V2 no longer requires a top-level `version` field.
# - Define environment variables in a `.env` file at the project root:
#
#   REDIS_URL=redis://localhost:6379
#   AFFILIATE_BASE_URL=https://affiliate-network.com
